;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Author: alexeev-prog                                                       ;;
;; Example ASM Program                                                        ;;
;; Program generated by FLEXPASM (github.com/alexeev-pro/flexpasm)            ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

format ELF executable 3
entry start


;;; PrintStringTemplate Hello, World!: Printing the string 'Hello, World!' to stdout ;;;
segment readable executable
start:
    MOV eax, 4
    MOV ebx, 1
    MOV ecx, msg
    MOV edx, msg_size
    INT 0x80

    MOV eax, 1
    XOR ebx, ebx
    INT 0x80

segment readable writeable
msg db 'Hello, World!', 0xA
msg_size = $-msg
