;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Author: alexeev-prog                                                                                               ;;
;; Example ASM Program                                                                                                ;;
;; Program generated by FLEXPASM (github.com/alexeev-pro/flexpasm)                                                    ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

format ELF64 executable;                        ; ELF64 EXECUTABLE
entry start                                     ; Set Start Entry


;; Segment readable executable in FASM is a directive for defining a section of code with readable and executable attributes.
segment readable executable

start:                                          ; Label start with 8 commands
	MOV RAX, 4                                      ; Loading 4 value into RAX register.
	MOV RCX, message                                ; Loading message value into RCX register.
	MOV RDX, message_size                           ; Loading message_size value into RDX register.
	INT 0x80                                        ; Call software interrupt 0x80: SYSCALL
	MOV RAX, 1                                      ; Loading 1 value into RAX register.
	XOR RBX, RBX                                    ; Exclusive OR operation RBX and RBX using XOR
	INT 0x80                                        ; Call software interrupt 0x80: SYSCALL
	JMP exit                                        ; Unconditional jump to label exit

exit:                                           ; Label exit with 3 commands
	; Exit with code -1
	MOV RAX, 1                                      ; Loading 1 value into RAX register.
	MOV RBX, -1                                     ; Loading -1 value into RBX register.
	INT 0x80                                        ; Call software interrupt 0x80: SYSCALL


;; Segment readable writeable in FASM is a definition of a segment of program data codes, where the attributes readable (the contents of the segment can be read) and writeable (program commands can both read codes and change their values) are specified for it.
segment readable writeable

message db 'Hello, World!', 0                   ; Var message (string)
message_size = $-message                        ; Var message (string) length